/* GeoBee Quest — curated fact bank.
 * Every fact is hand-authored and reviewable. No AI-generated content at runtime.
 * Tiers: 1 (easiest) … 5 (championship). Question styles modeled on
 * NSF Junior Geography Bee (written MCQ + oral) and IAC/International
 * Geography Bee elementary formats.
 *
 * Country fields: n=name, c=capital, k=continent, f=flag emoji, t=tier,
 *                 ct=capital-question tier override, x=fun fact
 * State fields:   n=name, c=capital, r=region, nick=nickname, t=tier, x=fun fact
 * Item fields:    q=question, a=answer, d=distractors, t=tier, x=fun fact,
 *                 alt=extra accepted typed answers
 */
window.GEO_DATA = (function () {

const COUNTRIES = [
  // ---- North America ----
  { n: "United States", c: "Washington, D.C.", k: "North America", f: "🇺🇸", t: 1, x: "Washington, D.C. isn't in any state — D.C. means District of Columbia." },
  { n: "Canada", c: "Ottawa", k: "North America", f: "🇨🇦", t: 1, ct: 2, x: "Canada is the second-largest country in the world by area." },
  { n: "Mexico", c: "Mexico City", k: "North America", f: "🇲🇽", t: 1, x: "Mexico City is built on the site of the ancient Aztec city Tenochtitlán." },
  { n: "Cuba", c: "Havana", k: "North America", f: "🇨🇺", t: 2, x: "Cuba is the largest island in the Caribbean Sea." },
  { n: "Jamaica", c: "Kingston", k: "North America", f: "🇯🇲", t: 3 },
  { n: "Panama", c: "Panama City", k: "North America", f: "🇵🇦", t: 3, x: "The Panama Canal lets ships cross between the Atlantic and Pacific Oceans." },
  { n: "Costa Rica", c: "San José", k: "North America", f: "🇨🇷", t: 3 },
  { n: "Guatemala", c: "Guatemala City", k: "North America", f: "🇬🇹", t: 4 },
  { n: "The Bahamas", c: "Nassau", k: "North America", f: "🇧🇸", t: 3 },
  { n: "Haiti", c: "Port-au-Prince", k: "North America", f: "🇭🇹", t: 4 },
  { n: "Dominican Republic", c: "Santo Domingo", k: "North America", f: "🇩🇴", t: 4 },
  { n: "Honduras", c: "Tegucigalpa", k: "North America", f: "🇭🇳", t: 5 },

  // ---- South America ----
  { n: "Brazil", c: "Brasília", k: "South America", f: "🇧🇷", t: 1, ct: 3, x: "Brasília was built brand-new in the 1950s to be the capital — not Rio!" },
  { n: "Argentina", c: "Buenos Aires", k: "South America", f: "🇦🇷", t: 2 },
  { n: "Chile", c: "Santiago", k: "South America", f: "🇨🇱", t: 2, x: "Chile is the longest, skinniest country in the world — over 2,600 miles long." },
  { n: "Peru", c: "Lima", k: "South America", f: "🇵🇪", t: 2, x: "Peru is home to Machu Picchu, the famous Inca city in the clouds." },
  { n: "Colombia", c: "Bogotá", k: "South America", f: "🇨🇴", t: 2 },
  { n: "Venezuela", c: "Caracas", k: "South America", f: "🇻🇪", t: 3, x: "Venezuela has Angel Falls, the tallest waterfall on Earth." },
  { n: "Ecuador", c: "Quito", k: "South America", f: "🇪🇨", t: 3, x: "Ecuador is named after the equator, which runs right through it." },
  { n: "Bolivia", c: "La Paz", k: "South America", f: "🇧🇴", t: 3, x: "La Paz is the highest capital city in the world." },
  { n: "Uruguay", c: "Montevideo", k: "South America", f: "🇺🇾", t: 4 },
  { n: "Paraguay", c: "Asunción", k: "South America", f: "🇵🇾", t: 4 },
  { n: "Guyana", c: "Georgetown", k: "South America", f: "🇬🇾", t: 5 },
  { n: "Suriname", c: "Paramaribo", k: "South America", f: "🇸🇷", t: 5 },

  // ---- Europe ----
  { n: "France", c: "Paris", k: "Europe", f: "🇫🇷", t: 1, x: "Paris is nicknamed the City of Light." },
  { n: "United Kingdom", c: "London", k: "Europe", f: "🇬🇧", t: 1, x: "The UK includes England, Scotland, Wales, and Northern Ireland." },
  { n: "Italy", c: "Rome", k: "Europe", f: "🇮🇹", t: 1, x: "Italy is shaped like a boot kicking the island of Sicily." },
  { n: "Spain", c: "Madrid", k: "Europe", f: "🇪🇸", t: 1 },
  { n: "Germany", c: "Berlin", k: "Europe", f: "🇩🇪", t: 1 },
  { n: "Russia", c: "Moscow", k: "Europe", f: "🇷🇺", t: 1, x: "Russia is the largest country on Earth — it spans Europe AND Asia across 11 time zones." },
  { n: "Greece", c: "Athens", k: "Europe", f: "🇬🇷", t: 2, x: "Athens is over 3,000 years old — one of the oldest cities in the world." },
  { n: "Portugal", c: "Lisbon", k: "Europe", f: "🇵🇹", t: 2 },
  { n: "Netherlands", c: "Amsterdam", k: "Europe", f: "🇳🇱", t: 2, x: "About a third of the Netherlands sits below sea level." },
  { n: "Switzerland", c: "Bern", k: "Europe", f: "🇨🇭", t: 2, ct: 3, x: "Many people guess Zurich or Geneva — but Switzerland's capital is Bern." },
  { n: "Sweden", c: "Stockholm", k: "Europe", f: "🇸🇪", t: 2 },
  { n: "Norway", c: "Oslo", k: "Europe", f: "🇳🇴", t: 2, x: "Norway's coast is carved with steep sea valleys called fjords." },
  { n: "Denmark", c: "Copenhagen", k: "Europe", f: "🇩🇰", t: 2 },
  { n: "Ireland", c: "Dublin", k: "Europe", f: "🇮🇪", t: 2, x: "Ireland is called the Emerald Isle because it's so green." },
  { n: "Poland", c: "Warsaw", k: "Europe", f: "🇵🇱", t: 3 },
  { n: "Austria", c: "Vienna", k: "Europe", f: "🇦🇹", t: 3 },
  { n: "Belgium", c: "Brussels", k: "Europe", f: "🇧🇪", t: 3 },
  { n: "Finland", c: "Helsinki", k: "Europe", f: "🇫🇮", t: 3 },
  { n: "Iceland", c: "Reykjavík", k: "Europe", f: "🇮🇸", t: 3, x: "Iceland is the land of fire and ice — volcanoes and glaciers side by side." },
  { n: "Ukraine", c: "Kyiv", k: "Europe", f: "🇺🇦", t: 3 },
  { n: "Czechia", c: "Prague", k: "Europe", f: "🇨🇿", t: 4 },
  { n: "Hungary", c: "Budapest", k: "Europe", f: "🇭🇺", t: 4, x: "Budapest is really two old cities — Buda and Pest — split by the Danube River." },
  { n: "Croatia", c: "Zagreb", k: "Europe", f: "🇭🇷", t: 4 },
  { n: "Romania", c: "Bucharest", k: "Europe", f: "🇷🇴", t: 4 },
  { n: "Bulgaria", c: "Sofia", k: "Europe", f: "🇧🇬", t: 4 },
  { n: "Serbia", c: "Belgrade", k: "Europe", f: "🇷🇸", t: 5 },
  { n: "Estonia", c: "Tallinn", k: "Europe", f: "🇪🇪", t: 5 },
  { n: "Latvia", c: "Riga", k: "Europe", f: "🇱🇻", t: 5 },
  { n: "Lithuania", c: "Vilnius", k: "Europe", f: "🇱🇹", t: 5 },
  { n: "Slovenia", c: "Ljubljana", k: "Europe", f: "🇸🇮", t: 5 },
  { n: "Slovakia", c: "Bratislava", k: "Europe", f: "🇸🇰", t: 5 },
  { n: "Albania", c: "Tirana", k: "Europe", f: "🇦🇱", t: 5 },

  // ---- Asia ----
  { n: "Japan", c: "Tokyo", k: "Asia", f: "🇯🇵", t: 1, x: "Tokyo is the most populous metropolitan area in the world." },
  { n: "China", c: "Beijing", k: "Asia", f: "🇨🇳", t: 1 },
  { n: "India", c: "New Delhi", k: "Asia", f: "🇮🇳", t: 1, x: "India has more people than any other country in the world." },
  { n: "South Korea", c: "Seoul", k: "Asia", f: "🇰🇷", t: 2 },
  { n: "Thailand", c: "Bangkok", k: "Asia", f: "🇹🇭", t: 2 },
  { n: "Singapore", c: "Singapore", k: "Asia", f: "🇸🇬", t: 2, x: "Singapore is a city, an island, AND a country all at once." },
  { n: "Turkey", c: "Ankara", k: "Asia", f: "🇹🇷", t: 2, ct: 3, x: "Istanbul is Turkey's biggest city, but Ankara is the capital. Turkey sits in both Europe and Asia." },
  { n: "Vietnam", c: "Hanoi", k: "Asia", f: "🇻🇳", t: 3 },
  { n: "Philippines", c: "Manila", k: "Asia", f: "🇵🇭", t: 3, x: "The Philippines is made of more than 7,000 islands." },
  { n: "Indonesia", c: "Jakarta", k: "Asia", f: "🇮🇩", t: 3, x: "Indonesia is the largest island country in the world — over 17,000 islands." },
  { n: "Malaysia", c: "Kuala Lumpur", k: "Asia", f: "🇲🇾", t: 3 },
  { n: "Israel", c: "Jerusalem", k: "Asia", f: "🇮🇱", t: 3 },
  { n: "Saudi Arabia", c: "Riyadh", k: "Asia", f: "🇸🇦", t: 3, x: "Saudi Arabia is mostly desert — including the huge Rub' al Khali, the Empty Quarter." },
  { n: "United Arab Emirates", c: "Abu Dhabi", k: "Asia", f: "🇦🇪", t: 3, x: "Dubai is the famous city, but Abu Dhabi is the capital of the UAE." },
  { n: "Nepal", c: "Kathmandu", k: "Asia", f: "🇳🇵", t: 3, x: "Nepal is home to Mount Everest and the only national flag that isn't a rectangle." },
  { n: "Iran", c: "Tehran", k: "Asia", f: "🇮🇷", t: 4 },
  { n: "Iraq", c: "Baghdad", k: "Asia", f: "🇮🇶", t: 4 },
  { n: "Pakistan", c: "Islamabad", k: "Asia", f: "🇵🇰", t: 4 },
  { n: "Bangladesh", c: "Dhaka", k: "Asia", f: "🇧🇩", t: 4 },
  { n: "Jordan", c: "Amman", k: "Asia", f: "🇯🇴", t: 4, x: "Jordan is home to Petra, an ancient city carved into rose-red rock." },
  { n: "Qatar", c: "Doha", k: "Asia", f: "🇶🇦", t: 4 },
  { n: "Mongolia", c: "Ulaanbaatar", k: "Asia", f: "🇲🇳", t: 4, x: "Ulaanbaatar is the coldest capital city on Earth." },
  { n: "Cambodia", c: "Phnom Penh", k: "Asia", f: "🇰🇭", t: 4 },
  { n: "Afghanistan", c: "Kabul", k: "Asia", f: "🇦🇫", t: 4 },
  { n: "Kazakhstan", c: "Astana", k: "Asia", f: "🇰🇿", t: 5, x: "Kazakhstan is the largest landlocked country in the world." },
  { n: "Uzbekistan", c: "Tashkent", k: "Asia", f: "🇺🇿", t: 5 },
  { n: "Myanmar", c: "Naypyidaw", k: "Asia", f: "🇲🇲", t: 5 },
  { n: "Laos", c: "Vientiane", k: "Asia", f: "🇱🇦", t: 5 },
  { n: "Bhutan", c: "Thimphu", k: "Asia", f: "🇧🇹", t: 5, x: "Bhutan measures success by Gross National Happiness." },
  { n: "Oman", c: "Muscat", k: "Asia", f: "🇴🇲", t: 5 },

  // ---- Africa ----
  { n: "Egypt", c: "Cairo", k: "Africa", f: "🇪🇬", t: 1, x: "Cairo is Africa's largest city, right beside the ancient pyramids." },
  { n: "Kenya", c: "Nairobi", k: "Africa", f: "🇰🇪", t: 2, x: "Kenya sits on the equator and is famous for safari animals." },
  { n: "South Africa", c: "Pretoria", k: "Africa", f: "🇿🇦", t: 2, ct: 4, x: "South Africa actually has three capitals — Pretoria is the main executive one." },
  { n: "Morocco", c: "Rabat", k: "Africa", f: "🇲🇦", t: 3, ct: 4, x: "Casablanca is Morocco's biggest city, but Rabat is the capital." },
  { n: "Nigeria", c: "Abuja", k: "Africa", f: "🇳🇬", t: 3, ct: 4, x: "Nigeria has more people than any other country in Africa." },
  { n: "Ethiopia", c: "Addis Ababa", k: "Africa", f: "🇪🇹", t: 3 },
  { n: "Algeria", c: "Algiers", k: "Africa", f: "🇩🇿", t: 3, x: "Algeria is the largest country in Africa by area." },
  { n: "Madagascar", c: "Antananarivo", k: "Africa", f: "🇲🇬", t: 3, ct: 5, x: "Madagascar is the fourth-largest island on Earth, full of animals found nowhere else — like lemurs!" },
  { n: "Ghana", c: "Accra", k: "Africa", f: "🇬🇭", t: 4 },
  { n: "Tanzania", c: "Dodoma", k: "Africa", f: "🇹🇿", t: 4, ct: 5, x: "Tanzania has Mount Kilimanjaro and the Serengeti plains." },
  { n: "Senegal", c: "Dakar", k: "Africa", f: "🇸🇳", t: 4 },
  { n: "Tunisia", c: "Tunis", k: "Africa", f: "🇹🇳", t: 4 },
  { n: "Libya", c: "Tripoli", k: "Africa", f: "🇱🇾", t: 4 },
  { n: "Sudan", c: "Khartoum", k: "Africa", f: "🇸🇩", t: 4, x: "In Khartoum, the Blue Nile and White Nile rivers join to form the Nile." },
  { n: "Uganda", c: "Kampala", k: "Africa", f: "🇺🇬", t: 4 },
  { n: "Somalia", c: "Mogadishu", k: "Africa", f: "🇸🇴", t: 4 },
  { n: "Rwanda", c: "Kigali", k: "Africa", f: "🇷🇼", t: 4, x: "Rwanda is nicknamed the Land of a Thousand Hills, home to mountain gorillas." },
  { n: "Democratic Republic of the Congo", c: "Kinshasa", k: "Africa", f: "🇨🇩", t: 4 },
  { n: "Zimbabwe", c: "Harare", k: "Africa", f: "🇿🇼", t: 5 },
  { n: "Zambia", c: "Lusaka", k: "Africa", f: "🇿🇲", t: 5 },
  { n: "Botswana", c: "Gaborone", k: "Africa", f: "🇧🇼", t: 5 },
  { n: "Namibia", c: "Windhoek", k: "Africa", f: "🇳🇦", t: 5 },
  { n: "Cameroon", c: "Yaoundé", k: "Africa", f: "🇨🇲", t: 5 },
  { n: "Ivory Coast", c: "Yamoussoukro", k: "Africa", f: "🇨🇮", t: 5 },
  { n: "Mali", c: "Bamako", k: "Africa", f: "🇲🇱", t: 5, x: "Mali is home to Timbuktu, an ancient city of scholars at the edge of the Sahara." },
  { n: "Mozambique", c: "Maputo", k: "Africa", f: "🇲🇿", t: 5 },
  { n: "Angola", c: "Luanda", k: "Africa", f: "🇦🇴", t: 5 },

  // ---- Oceania ----
  { n: "Australia", c: "Canberra", k: "Oceania", f: "🇦🇺", t: 1, ct: 3, x: "Sydney is bigger, but Canberra is Australia's capital. Australia is a country AND a continent!" },
  { n: "New Zealand", c: "Wellington", k: "Oceania", f: "🇳🇿", t: 2, ct: 3, x: "Wellington is the southernmost capital city of any country." },
  { n: "Fiji", c: "Suva", k: "Oceania", f: "🇫🇯", t: 4 },
  { n: "Papua New Guinea", c: "Port Moresby", k: "Oceania", f: "🇵🇬", t: 4, x: "Papua New Guinea has over 800 languages — more than any other country." },
  { n: "Samoa", c: "Apia", k: "Oceania", f: "🇼🇸", t: 5 },
  { n: "Tonga", c: "Nukuʻalofa", k: "Oceania", f: "🇹🇴", t: 5 },
];

const STATES = [
  // r: West | Southwest | Midwest | Southeast | Northeast; t = capital-question tier
  { n: "Washington", c: "Olympia", r: "West", nick: "The Evergreen State", t: 1, x: "Your home state! Olympia is the capital, but Seattle is the biggest city." },
  { n: "California", c: "Sacramento", r: "West", nick: "The Golden State", t: 1, x: "Many guess Los Angeles, but Sacramento is California's capital." },
  { n: "Texas", c: "Austin", r: "Southwest", nick: "The Lone Star State", t: 1, x: "Texas is the biggest state in the lower 48." },
  { n: "New York", c: "Albany", r: "Northeast", nick: "The Empire State", t: 2, x: "New York City is huge, but little Albany is the capital." },
  { n: "Florida", c: "Tallahassee", r: "Southeast", nick: "The Sunshine State", t: 2 },
  { n: "Hawaii", c: "Honolulu", r: "West", nick: "The Aloha State", t: 1, x: "Hawaii is the only US state made entirely of islands." },
  { n: "Alaska", c: "Juneau", r: "West", nick: "The Last Frontier", t: 2, x: "Juneau can't be reached by road — only by boat or plane! Alaska is the largest state." },
  { n: "Oregon", c: "Salem", r: "West", nick: "The Beaver State", t: 2, x: "Oregon is Washington's neighbor to the south." },
  { n: "Idaho", c: "Boise", r: "West", nick: "The Gem State", t: 2, x: "Idaho, Washington's eastern neighbor, is famous for potatoes." },
  { n: "Nevada", c: "Carson City", r: "West", nick: "The Silver State", t: 3, x: "Las Vegas is the famous city, but Carson City is the capital." },
  { n: "Arizona", c: "Phoenix", r: "Southwest", nick: "The Grand Canyon State", t: 1 },
  { n: "Colorado", c: "Denver", r: "West", nick: "The Centennial State", t: 1, x: "Denver is called the Mile High City — exactly one mile above sea level." },
  { n: "Utah", c: "Salt Lake City", r: "West", nick: "The Beehive State", t: 2 },
  { n: "New Mexico", c: "Santa Fe", r: "Southwest", nick: "The Land of Enchantment", t: 3, x: "Santa Fe is the oldest state capital in the USA, founded in 1610." },
  { n: "Montana", c: "Helena", r: "West", nick: "The Treasure State", t: 4 },
  { n: "Wyoming", c: "Cheyenne", r: "West", nick: "The Equality State", t: 4, x: "Wyoming has the fewest people of any state — but it has Yellowstone!" },
  { n: "Oklahoma", c: "Oklahoma City", r: "Southwest", nick: "The Sooner State", t: 2 },
  { n: "Kansas", c: "Topeka", r: "Midwest", nick: "The Sunflower State", t: 3 },
  { n: "Nebraska", c: "Lincoln", r: "Midwest", nick: "The Cornhusker State", t: 3 },
  { n: "North Dakota", c: "Bismarck", r: "Midwest", nick: "The Peace Garden State", t: 4 },
  { n: "South Dakota", c: "Pierre", r: "Midwest", nick: "The Mount Rushmore State", t: 5, x: "Pierre is one of the trickiest capitals — and Mount Rushmore is here." },
  { n: "Minnesota", c: "Saint Paul", r: "Midwest", nick: "The Land of 10,000 Lakes", t: 3, x: "Saint Paul and Minneapolis together are called the Twin Cities." },
  { n: "Iowa", c: "Des Moines", r: "Midwest", nick: "The Hawkeye State", t: 3 },
  { n: "Missouri", c: "Jefferson City", r: "Midwest", nick: "The Show-Me State", t: 5, x: "Not St. Louis, not Kansas City — Jefferson City is the capital." },
  { n: "Wisconsin", c: "Madison", r: "Midwest", nick: "The Badger State", t: 3, x: "Wisconsin is America's Dairyland — famous for cheese." },
  { n: "Illinois", c: "Springfield", r: "Midwest", nick: "The Prairie State", t: 3, x: "Chicago is giant, but Springfield — Abraham Lincoln's hometown — is the capital." },
  { n: "Michigan", c: "Lansing", r: "Midwest", nick: "The Great Lakes State", t: 4, x: "Michigan touches four of the five Great Lakes and looks like a mitten." },
  { n: "Indiana", c: "Indianapolis", r: "Midwest", nick: "The Hoosier State", t: 2 },
  { n: "Ohio", c: "Columbus", r: "Midwest", nick: "The Buckeye State", t: 3 },
  { n: "Kentucky", c: "Frankfort", r: "Southeast", nick: "The Bluegrass State", t: 5, x: "Not Louisville or Lexington — Frankfort is Kentucky's capital." },
  { n: "Tennessee", c: "Nashville", r: "Southeast", nick: "The Volunteer State", t: 2, x: "Nashville is called Music City, the home of country music." },
  { n: "Arkansas", c: "Little Rock", r: "Southeast", nick: "The Natural State", t: 3 },
  { n: "Louisiana", c: "Baton Rouge", r: "Southeast", nick: "The Pelican State", t: 4, x: "New Orleans is the famous city, but Baton Rouge — French for 'red stick' — is the capital." },
  { n: "Mississippi", c: "Jackson", r: "Southeast", nick: "The Magnolia State", t: 3 },
  { n: "Alabama", c: "Montgomery", r: "Southeast", nick: "The Yellowhammer State", t: 3 },
  { n: "Georgia", c: "Atlanta", r: "Southeast", nick: "The Peach State", t: 1 },
  { n: "South Carolina", c: "Columbia", r: "Southeast", nick: "The Palmetto State", t: 4 },
  { n: "North Carolina", c: "Raleigh", r: "Southeast", nick: "The Tar Heel State", t: 3 },
  { n: "Virginia", c: "Richmond", r: "Southeast", nick: "The Old Dominion", t: 3 },
  { n: "West Virginia", c: "Charleston", r: "Southeast", nick: "The Mountain State", t: 4 },
  { n: "Maryland", c: "Annapolis", r: "Northeast", nick: "The Old Line State", t: 4, x: "Annapolis is home to the US Naval Academy." },
  { n: "Delaware", c: "Dover", r: "Northeast", nick: "The First State", t: 4, x: "Delaware was the first state to join the USA in 1787." },
  { n: "New Jersey", c: "Trenton", r: "Northeast", nick: "The Garden State", t: 4 },
  { n: "Pennsylvania", c: "Harrisburg", r: "Northeast", nick: "The Keystone State", t: 4, x: "Philadelphia is the big city, but Harrisburg is the capital." },
  { n: "Connecticut", c: "Hartford", r: "Northeast", nick: "The Constitution State", t: 4 },
  { n: "Rhode Island", c: "Providence", r: "Northeast", nick: "The Ocean State", t: 3, x: "Rhode Island is the smallest state — 425 of them could fit inside Alaska." },
  { n: "Massachusetts", c: "Boston", r: "Northeast", nick: "The Bay State", t: 2 },
  { n: "Vermont", c: "Montpelier", r: "Northeast", nick: "The Green Mountain State", t: 5, x: "Montpelier is the smallest state capital in America — and makes lots of maple syrup." },
  { n: "New Hampshire", c: "Concord", r: "Northeast", nick: "The Granite State", t: 4 },
  { n: "Maine", c: "Augusta", r: "Northeast", nick: "The Pine Tree State", t: 4, x: "Maine is the only state whose name is one syllable." },
];

// Custom question items ------------------------------------------------------

const MAPS = [
  { q: "How many continents are there on Earth?", a: "7", d: ["5", "6", "8"], t: 1, alt: ["seven"], x: "Asia, Africa, North America, South America, Antarctica, Europe, and Australia." },
  { q: "How many oceans are there on Earth?", a: "5", d: ["3", "4", "7"], t: 1, alt: ["five"], x: "Pacific, Atlantic, Indian, Southern, and Arctic." },
  { q: "What is the imaginary line around the middle of the Earth called?", a: "The equator", d: ["The prime meridian", "The North Pole", "The horizon"], t: 1, alt: ["equator"], x: "The equator divides Earth into the Northern and Southern Hemispheres." },
  { q: "Which direction is opposite of north?", a: "South", d: ["East", "West", "Up"], t: 1 },
  { q: "Which direction does the sun rise from?", a: "East", d: ["West", "North", "South"], t: 1, x: "The sun rises in the east and sets in the west." },
  { q: "What are the four main directions on a compass called?", a: "Cardinal directions", d: ["Compass angles", "Map lines", "Pole points"], t: 2, alt: ["cardinal"], x: "North, south, east, and west are the cardinal directions." },
  { q: "What is a round model of the Earth called?", a: "A globe", d: ["An atlas", "A compass", "A chart"], t: 1, alt: ["globe"] },
  { q: "What is a book of maps called?", a: "An atlas", d: ["A globe", "An almanac", "A dictionary"], t: 2, alt: ["atlas"] },
  { q: "What part of a map explains what its symbols mean?", a: "The key (or legend)", d: ["The compass rose", "The scale", "The title"], t: 2, alt: ["key", "legend", "map key", "map legend"] },
  { q: "What symbol on a map shows directions?", a: "The compass rose", d: ["The key", "The scale", "The grid"], t: 2, alt: ["compass rose", "compass"] },
  { q: "The equator divides Earth into which two hemispheres?", a: "Northern and Southern", d: ["Eastern and Western", "Upper and Lower", "Left and Right"], t: 2, alt: ["northern and southern hemispheres", "north and south"] },
  { q: "What is the imaginary line at 0° longitude called?", a: "The prime meridian", d: ["The equator", "The Tropic of Cancer", "The date line"], t: 3, alt: ["prime meridian"], x: "It runs through Greenwich, England, splitting Earth into Eastern and Western Hemispheres." },
  { q: "Lines that run east–west around the globe measure what?", a: "Latitude", d: ["Longitude", "Altitude", "Distance"], t: 3, alt: ["latitude"], x: "A trick to remember: latitude lines are 'flat' like rungs of a ladder." },
  { q: "Lines that run north–south from pole to pole measure what?", a: "Longitude", d: ["Latitude", "Altitude", "Temperature"], t: 3, alt: ["longitude"] },
  { q: "Where is the coldest place on Earth, the South Pole, located?", a: "Antarctica", d: ["The Arctic Ocean", "Greenland", "Alaska"], t: 2, x: "The South Pole sits on the continent of Antarctica; the North Pole is on frozen ocean." },
  { q: "The North Pole is located on frozen parts of which ocean?", a: "The Arctic Ocean", d: ["The Pacific Ocean", "The Atlantic Ocean", "The Southern Ocean"], t: 3, alt: ["arctic ocean", "arctic"], x: "There's no land at the North Pole — just floating sea ice." },
  { q: "What do we call the direction halfway between north and east?", a: "Northeast", d: ["Northwest", "Southeast", "East-north"], t: 2, alt: ["north east", "ne"], x: "Northeast, northwest, southeast and southwest are the intermediate directions." },
  { q: "Which imaginary line is north of the equator: the Tropic of Cancer or the Tropic of Capricorn?", a: "The Tropic of Cancer", d: ["The Tropic of Capricorn", "The Antarctic Circle", "The prime meridian"], t: 4, alt: ["tropic of cancer", "cancer"] },
  { q: "What does a map's scale tell you?", a: "How map distance compares to real distance", d: ["Which way is north", "What the symbols mean", "How high mountains are"], t: 4, x: "A scale might show that one inch on the map equals 100 miles on the ground." },
  { q: "What is a person who makes maps called?", a: "A cartographer", d: ["A geologist", "A navigator", "An astronomer"], t: 4, alt: ["cartographer"] },
  { q: "Which needle direction does a compass point to?", a: "North", d: ["South", "East", "West"], t: 2, x: "A compass needle is pulled toward Earth's magnetic north." },
  { q: "What is the latitude of the equator?", a: "0 degrees", d: ["90 degrees", "45 degrees", "180 degrees"], t: 4, alt: ["0", "zero", "zero degrees", "0°"] },
  { q: "The 90°N point on Earth is better known as what?", a: "The North Pole", d: ["The South Pole", "The equator", "The prime meridian"], t: 5, alt: ["north pole"] },
];

const CONTINENTS = [
  { q: "Which is the largest continent?", a: "Asia", d: ["Africa", "North America", "Europe"], t: 1, x: "Asia holds about 60% of all the people on Earth." },
  { q: "Which is the smallest continent?", a: "Australia", d: ["Europe", "Antarctica", "South America"], t: 1 },
  { q: "Which is the coldest continent?", a: "Antarctica", d: ["Europe", "North America", "Asia"], t: 1, x: "Antarctica is also the driest continent — it's actually a huge frozen desert." },
  { q: "Which is the second-largest continent?", a: "Africa", d: ["Asia", "North America", "South America"], t: 3 },
  { q: "On which continent is the United States?", a: "North America", d: ["South America", "Europe", "Australia"], t: 1 },
  { q: "Which continent has no permanent human residents?", a: "Antarctica", d: ["Australia", "Africa", "South America"], t: 2, x: "Only visiting scientists live there, in research stations." },
  { q: "Which continent is both a country and a continent?", a: "Australia", d: ["Greenland", "India", "Antarctica"], t: 2 },
  { q: "Which is the largest ocean?", a: "The Pacific Ocean", d: ["The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"], t: 1, alt: ["pacific", "pacific ocean"], x: "The Pacific is bigger than all the land on Earth put together!" },
  { q: "Which is the smallest ocean?", a: "The Arctic Ocean", d: ["The Southern Ocean", "The Indian Ocean", "The Atlantic Ocean"], t: 2, alt: ["arctic", "arctic ocean"] },
  { q: "Which ocean lies between North America and Europe?", a: "The Atlantic Ocean", d: ["The Pacific Ocean", "The Indian Ocean", "The Arctic Ocean"], t: 2, alt: ["atlantic", "atlantic ocean"] },
  { q: "Which ocean is west of the United States?", a: "The Pacific Ocean", d: ["The Atlantic Ocean", "The Arctic Ocean", "The Indian Ocean"], t: 1, alt: ["pacific", "pacific ocean"], x: "From a Washington beach, you're looking at the Pacific." },
  { q: "Which ocean surrounds Antarctica?", a: "The Southern Ocean", d: ["The Arctic Ocean", "The Atlantic Ocean", "The Indian Ocean"], t: 3, alt: ["southern", "southern ocean", "antarctic ocean"] },
  { q: "Which ocean is the second largest?", a: "The Atlantic Ocean", d: ["The Indian Ocean", "The Pacific Ocean", "The Southern Ocean"], t: 3, alt: ["atlantic", "atlantic ocean"] },
  { q: "Which ocean lies between Africa and Australia?", a: "The Indian Ocean", d: ["The Atlantic Ocean", "The Pacific Ocean", "The Southern Ocean"], t: 3, alt: ["indian", "indian ocean"] },
  { q: "Europe and Asia together are sometimes called what?", a: "Eurasia", d: ["Eurabia", "Asiope", "Oceania"], t: 4, alt: ["eurasia"], x: "Europe and Asia share one giant landmass." },
  { q: "The equator crosses which of these continents?", a: "Africa", d: ["Europe", "North America", "Antarctica"], t: 3, x: "The equator also crosses South America and the islands of Southeast Asia." },
  { q: "Which continent has the most people?", a: "Asia", d: ["Africa", "Europe", "North America"], t: 2 },
  { q: "Which two continents are entirely in the Southern Hemisphere?", a: "Australia and Antarctica", d: ["Africa and South America", "Asia and Australia", "South America and Antarctica"], t: 4 },
  { q: "Which continent has the most countries?", a: "Africa", d: ["Asia", "Europe", "South America"], t: 4, x: "Africa has 54 countries — more than any other continent." },
  { q: "North America and South America are connected by which narrow strip of land?", a: "Central America", d: ["The Middle East", "The Caribbean", "Patagonia"], t: 3, alt: ["central america", "the isthmus of panama", "isthmus of panama"] },
];

const US_PHYSICAL = [
  { q: "Which great river flows south through the middle of the USA into the Gulf of Mexico?", a: "The Mississippi River", d: ["The Colorado River", "The Columbia River", "The Hudson River"], t: 1, alt: ["mississippi", "mississippi river"], x: "Native Americans called it the 'Father of Waters.'" },
  { q: "Which is the longest river in the United States?", a: "The Missouri River", d: ["The Mississippi River", "The Rio Grande", "The Ohio River"], t: 5, alt: ["missouri", "missouri river"], x: "Surprise! The Missouri beats the Mississippi by about 100 miles." },
  { q: "Which major mountain range runs down the western United States?", a: "The Rocky Mountains", d: ["The Appalachian Mountains", "The Alps", "The Andes"], t: 2, alt: ["rockies", "rocky mountains", "the rockies"] },
  { q: "Which older, lower mountain range runs along the eastern United States?", a: "The Appalachian Mountains", d: ["The Rocky Mountains", "The Cascade Range", "The Sierra Nevada"], t: 3, alt: ["appalachians", "appalachian mountains", "the appalachians"] },
  { q: "The Grand Canyon was carved by which river?", a: "The Colorado River", d: ["The Mississippi River", "The Missouri River", "The Snake River"], t: 2, alt: ["colorado", "colorado river"], x: "The Colorado River took millions of years to carve the canyon a mile deep." },
  { q: "In which state is the Grand Canyon?", a: "Arizona", d: ["Colorado", "Utah", "Nevada"], t: 2 },
  { q: "What is the tallest mountain in North America?", a: "Denali", d: ["Mount Rainier", "Mount Whitney", "Pikes Peak"], t: 4, alt: ["denali", "mount mckinley", "mckinley"], x: "Denali, in Alaska, rises 20,310 feet. Its name means 'the tall one.'" },
  { q: "How many Great Lakes are there?", a: "5", d: ["3", "4", "7"], t: 2, alt: ["five"], x: "Remember them with HOMES: Huron, Ontario, Michigan, Erie, Superior." },
  { q: "Which is the largest of the Great Lakes?", a: "Lake Superior", d: ["Lake Michigan", "Lake Huron", "Lake Erie"], t: 3, alt: ["superior", "lake superior"], x: "Lake Superior is the largest freshwater lake in the world by surface area." },
  { q: "Which Great Lake is entirely inside the United States?", a: "Lake Michigan", d: ["Lake Superior", "Lake Huron", "Lake Ontario"], t: 5, alt: ["michigan", "lake michigan"], x: "The other four Great Lakes are shared with Canada." },
  { q: "Niagara Falls sits on the border between the USA and which country?", a: "Canada", d: ["Mexico", "France", "Iceland"], t: 2 },
  { q: "Which river forms much of the border between Texas and Mexico?", a: "The Rio Grande", d: ["The Colorado River", "The Mississippi River", "The Pecos River"], t: 3, alt: ["rio grande"], x: "Rio Grande is Spanish for 'big river.'" },
  { q: "What was America's first national park, famous for the Old Faithful geyser?", a: "Yellowstone", d: ["Yosemite", "Grand Canyon", "Olympic"], t: 2, alt: ["yellowstone", "yellowstone national park"], x: "Yellowstone became the world's first national park in 1872." },
  { q: "What is the hottest, lowest place in North America?", a: "Death Valley", d: ["The Mojave Desert", "The Grand Canyon", "The Everglades"], t: 3, alt: ["death valley"], x: "Death Valley in California once hit 134°F — a world record." },
  { q: "Which huge Florida wetland is nicknamed the 'River of Grass'?", a: "The Everglades", d: ["The Bayou", "The Okefenokee", "The Salt Marsh"], t: 3, alt: ["everglades", "the everglades"], x: "The Everglades is home to alligators AND crocodiles." },
  { q: "Which big salty lake is next to a state capital in Utah?", a: "The Great Salt Lake", d: ["Lake Tahoe", "Lake Powell", "Crater Lake"], t: 3, alt: ["great salt lake"], x: "It's so salty you float like a cork!" },
  { q: "What is the deepest lake in the United States?", a: "Crater Lake", d: ["Lake Superior", "Lake Tahoe", "Great Salt Lake"], t: 4, alt: ["crater lake"], x: "Crater Lake in Oregon fills the crater of an old volcano — 1,943 feet deep." },
  { q: "What is the tallest mountain in Washington state?", a: "Mount Rainier", d: ["Mount St. Helens", "Mount Baker", "Mount Olympus"], t: 1, alt: ["rainier", "mount rainier", "mt rainier"], x: "On clear days you can see Mount Rainier from Bothell — it's a sleeping volcano!" },
  { q: "Which Washington volcano famously erupted in 1980?", a: "Mount St. Helens", d: ["Mount Rainier", "Mount Hood", "Mount Adams"], t: 2, alt: ["mount st helens", "st helens", "mt st helens", "mount saint helens"], x: "The eruption blew 1,300 feet off the top of the mountain." },
  { q: "Which mountain range do Mount Rainier and Mount St. Helens belong to?", a: "The Cascade Range", d: ["The Rocky Mountains", "The Olympic Mountains", "The Sierra Nevada"], t: 3, alt: ["cascades", "cascade range", "the cascades", "cascade mountains"] },
  { q: "Seattle sits on the shore of which body of water?", a: "Puget Sound", d: ["San Francisco Bay", "The Columbia River", "Lake Washington"], t: 2, alt: ["puget sound"], x: "Puget Sound is a deep arm of the Pacific Ocean, full of orcas and ferries." },
  { q: "Which big river forms most of the border between Washington and Oregon?", a: "The Columbia River", d: ["The Snake River", "The Willamette River", "The Yakima River"], t: 2, alt: ["columbia", "columbia river"], x: "The Columbia is the largest river flowing into the Pacific from North America." },
  { q: "In which state is the huge Yosemite National Park with giant sequoia trees?", a: "California", d: ["Oregon", "Colorado", "Montana"], t: 3, x: "Giant sequoias are the biggest trees on Earth." },
  { q: "The Ohio River flows into which larger river?", a: "The Mississippi River", d: ["The Missouri River", "The Hudson River", "The Rio Grande"], t: 4, alt: ["mississippi", "mississippi river"] },
  { q: "Which desert covers much of the southwestern United States near Las Vegas?", a: "The Mojave Desert", d: ["The Sahara Desert", "The Gobi Desert", "The Sonoran Forest"], t: 4, alt: ["mojave", "mojave desert"], x: "The Mojave is home to Joshua trees and Death Valley." },
  { q: "Which two states do NOT touch any other state?", a: "Alaska and Hawaii", d: ["Texas and Florida", "Washington and Maine", "California and Nevada"], t: 2, x: "Alaska touches Canada, and Hawaii is islands far out in the Pacific." },
  { q: "Which state is farthest north in the whole USA?", a: "Alaska", d: ["Washington", "Maine", "Minnesota"], t: 2, x: "Part of Alaska even crosses the Arctic Circle." },
  { q: "Which mountain has the faces of four presidents carved into it?", a: "Mount Rushmore", d: ["Mount Rainier", "Pikes Peak", "Stone Mountain"], t: 1, alt: ["rushmore", "mount rushmore"], x: "Washington, Jefferson, Theodore Roosevelt, and Lincoln — each face is 60 feet tall." },
  { q: "In which state is Mount Rushmore?", a: "South Dakota", d: ["North Dakota", "Wyoming", "Colorado"], t: 2 },
  { q: "Which US state has an active volcano called Kilauea?", a: "Hawaii", d: ["Alaska", "Washington", "California"], t: 3, x: "Kilauea is one of the most active volcanoes on Earth." },
];

const US_LANDMARKS = [
  { q: "In which city is the Statue of Liberty?", a: "New York City", d: ["Washington, D.C.", "Boston", "Philadelphia"], t: 1, alt: ["new york", "new york city", "nyc"], x: "She was a gift from France in 1886 and stands on Liberty Island." },
  { q: "Which country gave the Statue of Liberty to the United States?", a: "France", d: ["United Kingdom", "Spain", "Italy"], t: 2 },
  { q: "In which city is the White House?", a: "Washington, D.C.", d: ["New York City", "Philadelphia", "Boston"], t: 1, alt: ["washington dc", "washington", "dc", "washington d.c."], x: "Every US president since John Adams has lived there." },
  { q: "The famous Golden Gate Bridge is in which city?", a: "San Francisco", d: ["Los Angeles", "Seattle", "San Diego"], t: 2, alt: ["san francisco"], x: "Its color is officially called 'International Orange.'" },
  { q: "The Space Needle is the famous tower of which city?", a: "Seattle", d: ["Portland", "San Francisco", "Chicago"], t: 1, alt: ["seattle"], x: "The Space Needle was built for the 1962 World's Fair — right near Bothell!" },
  { q: "The Gateway Arch, the tallest monument in the USA, is in which city?", a: "St. Louis", d: ["Chicago", "Kansas City", "Memphis"], t: 3, alt: ["st louis", "saint louis", "st. louis"], x: "The 630-foot arch celebrates St. Louis as the 'Gateway to the West.'" },
  { q: "In which city is the Liberty Bell?", a: "Philadelphia", d: ["Washington, D.C.", "Boston", "New York City"], t: 3, alt: ["philadelphia", "philly"], x: "The Liberty Bell got its famous crack in the 1800s." },
  { q: "The Hollywood Sign overlooks which city?", a: "Los Angeles", d: ["San Francisco", "Las Vegas", "Miami"], t: 1, alt: ["los angeles", "la"] },
  { q: "The Alamo is a famous historic site in which Texas city?", a: "San Antonio", d: ["Houston", "Dallas", "Austin"], t: 4, alt: ["san antonio"] },
  { q: "Pearl Harbor is a famous historic site in which state?", a: "Hawaii", d: ["California", "Florida", "Alaska"], t: 3 },
  { q: "The Empire State Building is in which city?", a: "New York City", d: ["Chicago", "Boston", "Washington, D.C."], t: 2, alt: ["new york", "new york city", "nyc"], x: "When it opened in 1931, it was the tallest building in the world." },
  { q: "Which memorial in Washington, D.C. honors the president on the penny?", a: "The Lincoln Memorial", d: ["The Washington Monument", "The Jefferson Memorial", "The Capitol"], t: 3, alt: ["lincoln memorial"], x: "Abraham Lincoln's statue inside is 19 feet tall." },
  { q: "What is the tall, pointed monument in Washington, D.C. called?", a: "The Washington Monument", d: ["The Lincoln Memorial", "The Space Needle", "The Gateway Arch"], t: 2, alt: ["washington monument"], x: "At 555 feet, it was once the tallest structure in the world." },
  { q: "The US Congress meets in which building in Washington, D.C.?", a: "The Capitol", d: ["The White House", "The Pentagon", "The Supreme Court"], t: 3, alt: ["capitol", "the capitol building", "capitol building", "us capitol"] },
  { q: "Disney World is in which state?", a: "Florida", d: ["California", "Texas", "New York"], t: 1, x: "Disney World in Orlando is the most-visited theme park resort on Earth. Disneyland is the one in California." },
];

const WORLD_PHYSICAL = [
  { q: "Which river is usually called the longest in the world?", a: "The Nile", d: ["The Amazon", "The Mississippi", "The Yangtze"], t: 2, alt: ["nile", "nile river", "the nile river"], x: "The Nile flows over 4,100 miles through Africa. Some scientists argue the Amazon is longer!" },
  { q: "Which river carries the most water in the world?", a: "The Amazon", d: ["The Nile", "The Mississippi", "The Congo"], t: 3, alt: ["amazon", "amazon river"], x: "The Amazon carries more water than the next seven biggest rivers combined." },
  { q: "On which continent is the Amazon Rainforest?", a: "South America", d: ["Africa", "Asia", "Australia"], t: 1, x: "The Amazon makes so much oxygen it's called the 'lungs of the Earth.'" },
  { q: "What is the tallest mountain in the world?", a: "Mount Everest", d: ["K2", "Denali", "Mount Kilimanjaro"], t: 1, alt: ["everest", "mount everest", "mt everest"], x: "Everest is 29,032 feet tall — and still growing a tiny bit each year!" },
  { q: "Mount Everest is part of which mountain range?", a: "The Himalayas", d: ["The Andes", "The Alps", "The Rockies"], t: 2, alt: ["himalayas", "the himalayas", "himalaya"] },
  { q: "Which country's border with Nepal runs across Mount Everest?", a: "China", d: ["India", "Bhutan", "Pakistan"], t: 5, x: "Everest sits right on the border of Nepal and China (Tibet)." },
  { q: "What is the second-tallest mountain in the world?", a: "K2", d: ["Kangchenjunga", "Denali", "Mont Blanc"], t: 5, alt: ["k2", "k-2"], x: "K2 is considered even harder to climb than Everest." },
  { q: "What is the largest hot desert in the world?", a: "The Sahara", d: ["The Gobi", "The Mojave", "The Atacama"], t: 1, alt: ["sahara", "sahara desert"], x: "The Sahara is almost as big as the entire United States." },
  { q: "On which continent is the Sahara Desert?", a: "Africa", d: ["Asia", "Australia", "South America"], t: 1 },
  { q: "Which cold desert stretches across Mongolia and China?", a: "The Gobi Desert", d: ["The Sahara", "The Kalahari", "The Outback"], t: 3, alt: ["gobi", "gobi desert"] },
  { q: "What is the driest desert in the world?", a: "The Atacama", d: ["The Sahara", "The Gobi", "The Mojave"], t: 5, alt: ["atacama", "atacama desert"], x: "Parts of Chile's Atacama Desert went 400 years without rain." },
  { q: "What is the longest mountain range in the world?", a: "The Andes", d: ["The Himalayas", "The Rockies", "The Alps"], t: 3, alt: ["andes", "the andes mountains", "andes mountains"], x: "The Andes run 4,300 miles down the west side of South America." },
  { q: "Which mountain range separates France and Italy from central Europe?", a: "The Alps", d: ["The Pyrenees", "The Urals", "The Carpathians"], t: 3, alt: ["alps", "the alps"], x: "Mont Blanc is the tallest peak in the Alps." },
  { q: "What is the tallest mountain in Africa?", a: "Mount Kilimanjaro", d: ["Mount Kenya", "Atlas Mountains", "Table Mountain"], t: 3, alt: ["kilimanjaro", "mount kilimanjaro", "mt kilimanjaro"], x: "Kilimanjaro has snow on top even though it's near the equator." },
  { q: "Which famous snow-capped volcano is a symbol of Japan?", a: "Mount Fuji", d: ["Mount Everest", "Krakatoa", "Mount Kilimanjaro"], t: 2, alt: ["fuji", "mount fuji", "mt fuji"] },
  { q: "What is the largest lake in the world?", a: "The Caspian Sea", d: ["Lake Superior", "Lake Victoria", "Lake Baikal"], t: 4, alt: ["caspian sea", "caspian"], x: "Even though it's called a sea, the Caspian is really a giant salty lake." },
  { q: "What is the deepest lake in the world?", a: "Lake Baikal", d: ["Lake Superior", "Crater Lake", "The Caspian Sea"], t: 4, alt: ["baikal", "lake baikal"], x: "Russia's Lake Baikal holds about one-fifth of all the fresh water on Earth." },
  { q: "What is the largest island in the world?", a: "Greenland", d: ["Madagascar", "Australia", "Great Britain"], t: 3, alt: ["greenland"], x: "Greenland is icy, and Iceland is green — the Vikings mixed up the names on purpose!" },
  { q: "What is the deepest place in all the oceans?", a: "The Mariana Trench", d: ["The Grand Canyon", "The Great Barrier Reef", "The Bermuda Triangle"], t: 3, alt: ["mariana trench", "marianas trench"], x: "It's nearly 7 miles deep — Everest would sink without a trace." },
  { q: "What is the world's largest coral reef, off the coast of Australia?", a: "The Great Barrier Reef", d: ["The Mariana Trench", "The Coral Triangle", "The Florida Keys"], t: 2, alt: ["great barrier reef"], x: "It's so big, astronauts can see it from space." },
  { q: "What is the tallest waterfall in the world?", a: "Angel Falls", d: ["Niagara Falls", "Victoria Falls", "Yosemite Falls"], t: 4, alt: ["angel falls"], x: "In Venezuela, water falls 3,212 feet — the drop is so long it turns to mist." },
  { q: "Victoria Falls lies on the border of Zambia and which country?", a: "Zimbabwe", d: ["Kenya", "South Africa", "Egypt"], t: 5, x: "Locals call it 'the smoke that thunders.'" },
  { q: "Which sea lies between Europe and Africa?", a: "The Mediterranean Sea", d: ["The Red Sea", "The Black Sea", "The Baltic Sea"], t: 2, alt: ["mediterranean", "mediterranean sea"] },
  { q: "Which sea separates Egypt from Saudi Arabia?", a: "The Red Sea", d: ["The Mediterranean Sea", "The Black Sea", "The Dead Sea"], t: 4, alt: ["red sea"] },
  { q: "Which canal in Egypt connects the Mediterranean and Red Seas?", a: "The Suez Canal", d: ["The Panama Canal", "The Erie Canal", "The Grand Canal"], t: 4, alt: ["suez", "suez canal"] },
  { q: "Which canal lets ships cut between the Atlantic and Pacific Oceans?", a: "The Panama Canal", d: ["The Suez Canal", "The Erie Canal", "The English Channel"], t: 3, alt: ["panama canal"], x: "Before the canal, ships had to sail all the way around South America." },
  { q: "Which sea is so salty that people float on top of it?", a: "The Dead Sea", d: ["The Red Sea", "The Black Sea", "The Caspian Sea"], t: 3, alt: ["dead sea"], x: "The Dead Sea shore is the lowest dry land on Earth." },
  { q: "Which river flows through London?", a: "The Thames", d: ["The Seine", "The Danube", "The Rhine"], t: 4, alt: ["thames", "river thames", "the river thames"] },
  { q: "Which river flows through Paris?", a: "The Seine", d: ["The Thames", "The Loire", "The Rhine"], t: 4, alt: ["seine", "the seine river", "seine river"] },
  { q: "Which is the longest river in Asia?", a: "The Yangtze", d: ["The Ganges", "The Mekong", "The Yellow River"], t: 5, alt: ["yangtze", "yangtze river"], x: "China's Yangtze is the third-longest river in the world." },
  { q: "Which European river flows through Vienna and Budapest?", a: "The Danube", d: ["The Rhine", "The Seine", "The Volga"], t: 5, alt: ["danube", "danube river"], x: "The Danube touches 10 countries — more than any other river." },
  { q: "Which huge grassland in Tanzania and Kenya is famous for lions and wildebeest?", a: "The Serengeti", d: ["The Outback", "The Pampas", "The Prairie"], t: 3, alt: ["serengeti"], x: "Every year, over a million wildebeest migrate across the Serengeti." },
  { q: "What is the dry middle of Australia called?", a: "The Outback", d: ["The Serengeti", "The Sahara", "The Bush Coast"], t: 2, alt: ["outback", "the australian outback"], x: "The Outback is home to kangaroos, emus, and the giant red rock Uluru." },
  { q: "The 'Ring of Fire,' where most volcanoes and earthquakes happen, circles which ocean?", a: "The Pacific Ocean", d: ["The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"], t: 3, alt: ["pacific", "pacific ocean"], x: "About 3 out of 4 of Earth's volcanoes sit on the Ring of Fire." },
  { q: "What giant red rock rises from the middle of Australia?", a: "Uluru", d: ["Table Mountain", "El Capitan", "The Devils Tower"], t: 4, alt: ["uluru", "ayers rock"], x: "Uluru is taller than the Eiffel Tower and sacred to Aboriginal Australians." },
  { q: "Which African river is the deepest in the world?", a: "The Congo River", d: ["The Nile", "The Zambezi", "The Niger"], t: 5, alt: ["congo", "congo river"], x: "The Congo plunges more than 700 feet deep in places." },
];

const WORLD_LANDMARKS = [
  { q: "In which city is the Eiffel Tower?", a: "Paris", d: ["London", "Rome", "Madrid"], t: 1, alt: ["paris"], x: "When it was built in 1889, many Parisians thought it was ugly. Now it's the symbol of France!" },
  { q: "In which country is the Great Wall?", a: "China", d: ["Japan", "India", "Mongolia"], t: 1, x: "All its walls together would stretch over 13,000 miles." },
  { q: "In which country are the Pyramids of Giza?", a: "Egypt", d: ["Mexico", "Peru", "Greece"], t: 1, x: "The Great Pyramid was the tallest building on Earth for almost 4,000 years." },
  { q: "What giant lion-bodied statue guards the pyramids of Giza?", a: "The Sphinx", d: ["The Colossus", "The Minotaur", "The Griffin"], t: 2, alt: ["sphinx", "great sphinx", "the great sphinx"] },
  { q: "Big Ben is a famous clock tower in which city?", a: "London", d: ["Paris", "New York City", "Dublin"], t: 2, alt: ["london"], x: "Big Ben is actually the name of the giant bell inside the tower." },
  { q: "The ancient Colosseum, where gladiators fought, is in which city?", a: "Rome", d: ["Athens", "Cairo", "Istanbul"], t: 2, alt: ["rome"], x: "The Colosseum could hold 50,000 people — like a modern stadium, 2,000 years ago." },
  { q: "In which country is the Taj Mahal?", a: "India", d: ["Pakistan", "Iran", "Turkey"], t: 2, x: "An emperor built the Taj Mahal out of white marble for his wife. It took 20,000 workers over 20 years." },
  { q: "The famous Opera House with sail-shaped roofs is in which Australian city?", a: "Sydney", d: ["Melbourne", "Canberra", "Auckland"], t: 2, alt: ["sydney"] },
  { q: "Machu Picchu, the mountain-top city of the Incas, is in which country?", a: "Peru", d: ["Mexico", "Brazil", "Chile"], t: 3, x: "Machu Picchu sits 7,970 feet up in the Andes and was 'lost' to outsiders for centuries." },
  { q: "The giant statue of Christ the Redeemer overlooks which city?", a: "Rio de Janeiro", d: ["São Paulo", "Buenos Aires", "Lima"], t: 3, alt: ["rio", "rio de janeiro"], x: "The statue stands on a mountain 2,300 feet above Rio, in Brazil." },
  { q: "In which country is the famous Leaning Tower of Pisa?", a: "Italy", d: ["France", "Spain", "Greece"], t: 3, x: "It started leaning while it was being built — the ground was too soft." },
  { q: "Stonehenge, the mysterious circle of giant stones, is in which country?", a: "England", d: ["Ireland", "France", "Scotland"], t: 3, alt: ["england", "united kingdom", "uk", "the united kingdom", "great britain"], x: "Stonehenge is about 5,000 years old — older than the pyramids." },
  { q: "The Parthenon is an ancient temple in which city?", a: "Athens", d: ["Rome", "Cairo", "Jerusalem"], t: 4, alt: ["athens"], x: "It was built for Athena, the Greek goddess the city is named after." },
  { q: "Petra, the ancient city carved into pink rock cliffs, is in which country?", a: "Jordan", d: ["Egypt", "Greece", "Morocco"], t: 4 },
  { q: "Angkor Wat, the largest temple in the world, is in which country?", a: "Cambodia", d: ["Thailand", "India", "Vietnam"], t: 4, x: "Angkor Wat even appears on Cambodia's flag." },
  { q: "The stepped pyramid of Chichén Itzá was built by the Maya in which country?", a: "Mexico", d: ["Egypt", "Peru", "Guatemala"], t: 3, x: "Twice a year, sunlight makes a shadow-snake slither down its steps." },
  { q: "The giant stone heads called moai stand on which Pacific island?", a: "Easter Island", d: ["Hawaii", "Fiji", "Galápagos"], t: 4, alt: ["easter island", "rapa nui"], x: "Nearly 1,000 moai statues watch over Easter Island, part of Chile." },
  { q: "The Burj Khalifa, the tallest building in the world, is in which city?", a: "Dubai", d: ["Abu Dhabi", "New York City", "Shanghai"], t: 3, alt: ["dubai"], x: "It's 2,717 feet tall — more than half a mile into the sky." },
  { q: "The fairy-tale Neuschwanstein Castle is in which country?", a: "Germany", d: ["France", "Switzerland", "Austria"], t: 5, x: "It inspired the castle in Disney's Sleeping Beauty." },
  { q: "The colorful onion-domed St. Basil's Cathedral stands in which city?", a: "Moscow", d: ["Kyiv", "Warsaw", "Istanbul"], t: 4, alt: ["moscow"], x: "It stands on Red Square, next to the Kremlin." },
  { q: "The Forbidden City, home of ancient emperors, is in which city?", a: "Beijing", d: ["Shanghai", "Tokyo", "Seoul"], t: 4, alt: ["beijing"], x: "It has 980 buildings and was off-limits to ordinary people for 500 years." },
  { q: "The Sagrada Família, a giant unfinished church, is in which Spanish city?", a: "Barcelona", d: ["Madrid", "Seville", "Lisbon"], t: 5, alt: ["barcelona"], x: "Construction started in 1882 — and it's still not finished!" },
  { q: "Which city has a famous 'Little Mermaid' statue by the harbor?", a: "Copenhagen", d: ["Oslo", "Amsterdam", "Stockholm"], t: 5, alt: ["copenhagen"], x: "It honors the fairy tale by Danish writer Hans Christian Andersen." },
];

const INDIA = [
  { q: "What is the capital of India?", a: "New Delhi", d: ["Mumbai", "Kolkata", "Chennai"], t: 1, alt: ["new delhi", "delhi"] },
  { q: "What is the largest city in India?", a: "Mumbai", d: ["New Delhi", "Bengaluru", "Jaipur"], t: 2, alt: ["mumbai", "bombay"], x: "Mumbai is home to Bollywood, India's giant movie industry." },
  { q: "Which mountain range forms India's northern border?", a: "The Himalayas", d: ["The Western Ghats", "The Andes", "The Alps"], t: 1, alt: ["himalayas", "the himalayas"], x: "Himalaya means 'home of snow' in Sanskrit." },
  { q: "Which is the holiest and most famous river of India?", a: "The Ganga (Ganges)", d: ["The Yamuna", "The Godavari", "The Indus"], t: 2, alt: ["ganga", "ganges", "the ganges", "ganges river", "river ganga"], x: "Millions of people visit the Ganga every year — it's India's national river." },
  { q: "In which city is the Taj Mahal?", a: "Agra", d: ["New Delhi", "Jaipur", "Mumbai"], t: 3, alt: ["agra"], x: "The Taj Mahal's white marble changes color with the light of the day." },
  { q: "Which desert lies in northwestern India?", a: "The Thar Desert", d: ["The Gobi", "The Sahara", "The Deccan"], t: 3, alt: ["thar", "thar desert", "the great indian desert"], x: "The Thar Desert is also called the Great Indian Desert." },
  { q: "The Gateway of India monument stands in which city?", a: "Mumbai", d: ["New Delhi", "Chennai", "Kochi"], t: 3, alt: ["mumbai", "bombay"] },
  { q: "India Gate, a famous war memorial arch, is in which city?", a: "New Delhi", d: ["Mumbai", "Agra", "Amritsar"], t: 3, alt: ["new delhi", "delhi"] },
  { q: "Which ocean lies to the south of India?", a: "The Indian Ocean", d: ["The Pacific Ocean", "The Atlantic Ocean", "The Arctic Ocean"], t: 1, alt: ["indian ocean", "indian"] },
  { q: "Which sea lies to the west of India?", a: "The Arabian Sea", d: ["The Bay of Bengal", "The Red Sea", "The South China Sea"], t: 2, alt: ["arabian sea"] },
  { q: "Which bay lies to the east of India?", a: "The Bay of Bengal", d: ["The Arabian Sea", "The Bay of Biscay", "The Persian Gulf"], t: 2, alt: ["bay of bengal"] },
  { q: "How many states does India have?", a: "28", d: ["25", "29", "50"], t: 3, alt: ["28", "twenty eight", "twenty-eight"], x: "India has 28 states plus 8 union territories." },
  { q: "Which is India's largest state by area?", a: "Rajasthan", d: ["Uttar Pradesh", "Maharashtra", "Kerala"], t: 4, x: "Rajasthan means 'Land of Kings' — it's full of forts and palaces." },
  { q: "Which Indian state has the most people?", a: "Uttar Pradesh", d: ["Maharashtra", "Rajasthan", "Tamil Nadu"], t: 4, alt: ["uttar pradesh", "up"], x: "If Uttar Pradesh were a country, it would be the 5th most populous in the world." },
  { q: "What is the southern tip of mainland India called?", a: "Kanyakumari", d: ["Kochi", "Mumbai", "Rameswaram"], t: 4, alt: ["kanyakumari", "cape comorin"], x: "At Kanyakumari you can watch the sun rise and set over the ocean from the same beach." },
  { q: "Which island chain of India lies in the Bay of Bengal?", a: "Andaman and Nicobar Islands", d: ["Lakshadweep", "Maldives", "Seychelles"], t: 4, alt: ["andaman and nicobar", "andaman", "andamans"] },
  { q: "Which city is called the 'Silicon Valley of India' for its tech companies?", a: "Bengaluru", d: ["Mumbai", "Hyderabad", "Pune"], t: 3, alt: ["bengaluru", "bangalore"], x: "Bengaluru is also called the Garden City for its parks." },
  { q: "The Charminar, a monument with four minarets, is in which city?", a: "Hyderabad", d: ["Bengaluru", "Chennai", "Lucknow"], t: 4, alt: ["hyderabad"], x: "Charminar means 'four minarets' in Urdu." },
  { q: "Which high, flat land covers much of southern India?", a: "The Deccan Plateau", d: ["The Tibetan Plateau", "The Gangetic Plain", "The Thar Desert"], t: 4, alt: ["deccan", "deccan plateau"] },
  { q: "Which mountain range runs along India's western coast?", a: "The Western Ghats", d: ["The Eastern Ghats", "The Himalayas", "The Aravallis"], t: 4, alt: ["western ghats"] },
  { q: "What is India's national animal?", a: "The Bengal tiger", d: ["The lion", "The elephant", "The peacock"], t: 2, alt: ["tiger", "bengal tiger", "the tiger"], x: "More than half the world's wild tigers live in India." },
  { q: "What is India's national bird?", a: "The peacock", d: ["The eagle", "The parrot", "The crane"], t: 2, alt: ["peacock"], x: "The peacock's tail can have more than 200 shimmering feathers." },
  { q: "Which giant mangrove forest, home of Bengal tigers, sits where the Ganga meets the sea?", a: "The Sundarbans", d: ["The Western Ghats", "The Thar", "The Nilgiris"], t: 5, alt: ["sundarbans", "the sunderbans", "sunderbans"], x: "The Sundarbans is the largest mangrove forest in the world." },
  { q: "Which seasonal winds bring heavy rains to India every summer?", a: "The monsoon", d: ["The trade winds", "Hurricanes", "The jet stream"], t: 3, alt: ["monsoon", "monsoons", "the monsoons"], x: "Farmers across India wait all year for the monsoon rains." },
  { q: "Which river of northeast India is so wide it has islands with towns on them?", a: "The Brahmaputra", d: ["The Ganga", "The Yamuna", "The Krishna"], t: 5, alt: ["brahmaputra", "brahmaputra river"], x: "Majuli, in the Brahmaputra, is one of the largest river islands in the world." },
  { q: "What is the highest mountain located fully or partly in India?", a: "Kangchenjunga", d: ["Mount Everest", "K2", "Nanda Devi"], t: 5, alt: ["kangchenjunga", "kanchenjunga"], x: "Kangchenjunga is the third-highest mountain in the world." },
  { q: "Which neighbor country lies just north of India in the Himalayas, with Kathmandu as its capital?", a: "Nepal", d: ["Bhutan", "Bangladesh", "Sri Lanka"], t: 3 },
  { q: "Which island country lies just off India's southern tip?", a: "Sri Lanka", d: ["Maldives", "Madagascar", "Indonesia"], t: 3, alt: ["sri lanka"], x: "Sri Lanka is shaped like a teardrop falling from India." },
  { q: "Kolkata sits on which river, a branch of the Ganga?", a: "The Hooghly", d: ["The Yamuna", "The Brahmaputra", "The Godavari"], t: 5, alt: ["hooghly", "hooghly river", "hugli"] },
  { q: "Which Indian city is famous for its Pink Palaces and is called the Pink City?", a: "Jaipur", d: ["Jodhpur", "Udaipur", "Agra"], t: 4, alt: ["jaipur"], x: "Jaipur's old city was painted pink in 1876 to welcome a royal visit." },
];

const CONCEPTS = [
  { q: "What do we call land with water on three sides, like Florida?", a: "A peninsula", d: ["An island", "An isthmus", "A delta"], t: 2, alt: ["peninsula"], x: "Italy and Florida are both famous peninsulas." },
  { q: "What do we call land completely surrounded by water?", a: "An island", d: ["A peninsula", "A cape", "A plateau"], t: 1, alt: ["island"] },
  { q: "What is a group or chain of many islands called?", a: "An archipelago", d: ["A peninsula", "A colony", "An atoll belt"], t: 4, alt: ["archipelago"], x: "Hawaii, Japan, and the Philippines are all archipelagos." },
  { q: "What is a narrow strip of land connecting two larger lands, like Panama?", a: "An isthmus", d: ["A strait", "A peninsula", "A ridge"], t: 4, alt: ["isthmus"] },
  { q: "What is a narrow waterway connecting two larger bodies of water?", a: "A strait", d: ["An isthmus", "A bay", "A canal"], t: 4, alt: ["strait"], x: "The Bering Strait separates Alaska from Russia — only 55 miles apart!" },
  { q: "What is the fan-shaped land where a river spreads out and meets the sea?", a: "A delta", d: ["A canyon", "A source", "A basin"], t: 3, alt: ["delta"], x: "The Mississippi and Nile both end in huge deltas." },
  { q: "What do we call the place where a river begins?", a: "Its source", d: ["Its mouth", "Its delta", "Its bank"], t: 3, alt: ["source", "the source"] },
  { q: "What do we call the place where a river empties into the sea?", a: "Its mouth", d: ["Its source", "Its head", "Its spring"], t: 3, alt: ["mouth", "the mouth"] },
  { q: "What is a smaller river that flows into a bigger river called?", a: "A tributary", d: ["A delta", "A canal", "A stream bed"], t: 4, alt: ["tributary"] },
  { q: "What is high, flat land raised above the area around it called?", a: "A plateau", d: ["A valley", "A plain", "A basin"], t: 3, alt: ["plateau"], x: "Plateaus are sometimes called tablelands because they're flat like tables." },
  { q: "What is the low land between mountains or hills called?", a: "A valley", d: ["A plateau", "A ridge", "A mesa"], t: 2, alt: ["valley"] },
  { q: "What is a huge, slow-moving river of ice called?", a: "A glacier", d: ["An iceberg", "A floe", "A snowfield"], t: 3, alt: ["glacier"], x: "Glaciers carved out Puget Sound and the Great Lakes long ago." },
  { q: "What is a mountain that can erupt with melted rock called?", a: "A volcano", d: ["A geyser", "A butte", "A crater lake"], t: 1, alt: ["volcano"], x: "The melted rock is called lava once it reaches the surface." },
  { q: "What makes a desert a desert?", a: "It gets very little rain", d: ["It is always hot", "It is covered in sand", "It has no animals"], t: 3, x: "That's why freezing Antarctica counts as the world's largest desert!" },
  { q: "What is the cold, treeless land around the Arctic called?", a: "Tundra", d: ["Savanna", "Prairie", "Taiga"], t: 4, alt: ["tundra", "the tundra"], x: "Under the tundra the ground stays frozen all year — it's called permafrost." },
  { q: "What is a warm grassland with scattered trees, like in East Africa, called?", a: "A savanna", d: ["A tundra", "A rainforest", "A marsh"], t: 4, alt: ["savanna", "savannah"] },
  { q: "What kind of forest is warm, wet, and bursting with more kinds of life than anywhere else?", a: "A rainforest", d: ["A pine forest", "A tundra", "A savanna"], t: 2, alt: ["rainforest", "tropical rainforest", "rain forest"] },
  { q: "What is a green, watery spot in a desert called?", a: "An oasis", d: ["A dune", "A mirage", "A delta"], t: 3, alt: ["oasis"] },
  { q: "What do we call a country with no coastline at all?", a: "Landlocked", d: ["Islandless", "Inland-tied", "Dry-bordered"], t: 4, alt: ["landlocked", "a landlocked country"], x: "Bolivia, Nepal, and Switzerland are all landlocked." },
  { q: "What is the biggest country in the world by area?", a: "Russia", d: ["Canada", "China", "United States"], t: 2, x: "Russia is almost twice as big as Canada, the runner-up." },
  { q: "What is the smallest country in the world?", a: "Vatican City", d: ["Monaco", "Singapore", "Fiji"], t: 3, alt: ["vatican city", "vatican", "the vatican"], x: "Vatican City, inside Rome, is smaller than many city parks." },
  { q: "Which country has the most people in the world?", a: "India", d: ["China", "United States", "Indonesia"], t: 2, x: "India passed China in 2023 — over 1.4 billion people." },
  { q: "Which US state has the most people?", a: "California", d: ["Texas", "New York", "Florida"], t: 3, x: "About 1 in 8 Americans lives in California." },
  { q: "What is the largest metropolitan city in the world?", a: "Tokyo", d: ["New York City", "London", "Cairo"], t: 4, alt: ["tokyo"], x: "The Tokyo area is home to about 37 million people." },
  { q: "When it is summer in the United States, what season is it in Australia?", a: "Winter", d: ["Summer", "Spring", "Autumn"], t: 3, x: "Seasons are opposite in the Northern and Southern Hemispheres." },
  { q: "Which country has the longest coastline in the world?", a: "Canada", d: ["Russia", "Australia", "United States"], t: 5, x: "Canada's coast, with all its islands, stretches over 150,000 miles." },
  { q: "What do we call molten rock AFTER it erupts from a volcano?", a: "Lava", d: ["Magma", "Ash", "Basalt seed"], t: 3, alt: ["lava"], x: "Underground it's called magma; above ground it's lava." },
  { q: "Earth's outer shell is broken into huge slow-moving slabs called what?", a: "Tectonic plates", d: ["Crust sheets", "Rock rafts", "Mantle lids"], t: 4, alt: ["tectonic plates", "plates", "plate tectonics"], x: "When plates bump and slide, we get earthquakes, volcanoes, and new mountains." },
  { q: "What is a deep valley with steep rocky walls, often carved by a river, called?", a: "A canyon", d: ["A delta", "A plateau", "A fjord"], t: 2, alt: ["canyon"] },
  { q: "What is a part of the ocean that reaches into the land, usually smaller than a gulf?", a: "A bay", d: ["A strait", "A lagoon", "A channel"], t: 3, alt: ["bay"], x: "A gulf is like a bay's big brother — the Gulf of Mexico is huge." },
];

// ---------------------------------------------------------------------------

const TOPICS = [
  { id: "maps",       name: "Maps & Globes",        emoji: "🧭", kind: "items", items: MAPS },
  { id: "usmap",      name: "US Map Challenge",     emoji: "🗺️", kind: "usmap" },
  { id: "worldmap",   name: "World Map Challenge",  emoji: "🌐", kind: "worldmap" },
  { id: "continents", name: "Continents & Oceans",  emoji: "🌍", kind: "items", items: CONTINENTS },
  { id: "states",     name: "US States & Capitals", emoji: "🗽", kind: "states" },
  { id: "usphys",     name: "US Rivers & Mountains", emoji: "🏞️", kind: "items", items: US_PHYSICAL },
  { id: "uslandmarks", name: "US Landmarks",        emoji: "🌉", kind: "items", items: US_LANDMARKS },
  { id: "capitals",   name: "World Capitals",       emoji: "🏛️", kind: "capitals" },
  { id: "flags",      name: "Flags of the World",   emoji: "🚩", kind: "flags" },
  { id: "worldphys",  name: "World Rivers & Mountains", emoji: "🏔️", kind: "items", items: WORLD_PHYSICAL },
  { id: "landmarks",  name: "World Landmarks",      emoji: "🗿", kind: "items", items: WORLD_LANDMARKS },
  { id: "india",      name: "India Geography",      emoji: "🇮🇳", kind: "items", items: INDIA },
  { id: "concepts",   name: "Geography Words & Wonders", emoji: "💡", kind: "items", items: CONCEPTS },
];

return { COUNTRIES, STATES, TOPICS };
})();
