/* Generates js/maps.js from public-domain Natural Earth data
 * (us-atlas + world-atlas npm packages, both derived from Natural Earth /
 * US Census — public domain). Run with:
 *   npm install us-atlas world-atlas topojson-client d3-geo
 *   node tools/generate-maps.js > ../js/maps.js   (or see OUT below)
 * Output: window.GEO_MAPS = { us: {viewBox, states:{name:{d,area}}},
 *                             world: {viewBox, countries:{name:{d,area}}} }
 */
const fs = require("fs");
const path = require("path");
const topojson = require("topojson-client");
const d3 = require("d3-geo");

function round1(pathStr) {
  return pathStr.replace(/(\d+\.\d+)/g, (m) => (+m).toFixed(1));
}

// ---- US states (pre-projected Albers, 975x610) ----
const usTopo = JSON.parse(fs.readFileSync(require.resolve("us-atlas/states-albers-10m.json"), "utf8"));
const usFeatures = topojson.feature(usTopo, usTopo.objects.states).features;
const usPath = d3.geoPath(); // identity — already projected
const us = {};
for (const f of usFeatures) {
  const name = f.properties.name;
  if (["Puerto Rico", "United States Virgin Islands", "Guam", "American Samoa", "Commonwealth of the Northern Mariana Islands", "District of Columbia"].includes(name)) continue;
  us[name] = { d: round1(usPath(f)), area: Math.round(d3.geoPath().area ? 0 : 0) };
  // planar bbox area for click-size gating
  const b = usPath.bounds(f);
  us[name].area = Math.round((b[1][0] - b[0][0]) * (b[1][1] - b[0][1]));
}

// ---- World countries (Natural Earth 110m, NaturalEarth1 projection) ----
const worldTopo = JSON.parse(fs.readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8"));
const worldFeatures = topojson.feature(worldTopo, worldTopo.objects.countries).features;
const projection = d3.geoNaturalEarth1().fitSize([960, 500], { type: "Sphere" });
const worldPath = d3.geoPath(projection);
// Natural Earth name → our data.js name
const ALIASES = {
  "United States of America": "United States",
  "Dem. Rep. Congo": "Democratic Republic of the Congo",
  "Côte d'Ivoire": "Ivory Coast",
  "Bahamas": "The Bahamas",
  "Dominican Rep.": "Dominican Republic",
  "Czech Republic": "Czechia",
  "Türkiye": "Turkey",
  "Bosnia and Herz.": "Bosnia and Herzegovina",
  "S. Sudan": "South Sudan",
};
const world = {};
for (const f of worldFeatures) {
  let name = f.properties.name;
  name = ALIASES[name] || name;
  const d = worldPath(f);
  if (!d) continue;
  const b = worldPath.bounds(f);
  world[name] = { d: round1(d), area: Math.round((b[1][0] - b[0][0]) * (b[1][1] - b[0][1])) };
}
// Land backdrop (all countries merged) for context
const land = round1(worldPath(topojson.merge(worldTopo, worldTopo.objects.countries.geometries)));

const out = `/* Generated by tools/generate-maps.js from us-atlas + world-atlas
 * (Natural Earth / US Census data, public domain). Do not edit by hand. */
window.GEO_MAPS = ${JSON.stringify({
  us: { viewBox: "0 0 975 610", states: us },
  world: { viewBox: "0 0 960 500", land, countries: world },
})};
`;
const OUT = path.join(__dirname, "..", "js", "maps.js");
fs.writeFileSync(OUT, out);
console.error(`wrote ${OUT}: ${Object.keys(us).length} states, ${Object.keys(world).length} countries, ${(out.length / 1024).toFixed(0)} KB`);
